spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
      routes:
      - id: PRODUCT-SERVER
        # lb代表从注册中心获取服务
        uri: lb://PRODUCT-SERVER
        predicates:
        # 转发该路径
        - Path=/PRODUCT-SERVER/**
        # 带前缀
        filters:
        - StripPrefix=1
      - id: ORDER-SERVER
        uri: lb://ORDER-SERVER
        predicates:
        - Path=/ORDER-SERVER/**
        filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
#服务注册中心端口号
server:
  port: 6400

#服务注册中心实例的主机名、端口
#是否向服务注册中心注册自己
#是否检索服务
#服务注册中心的配置内容，指定服务注册中心的位置
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/